// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// gd_c
double gd_c(NumericMatrix A, NumericMatrix B, double p, bool modified);
RcppExport SEXP _ecr3vis_gd_c(SEXP ASEXP, SEXP BSEXP, SEXP pSEXP, SEXP modifiedSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type A(ASEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type B(BSEXP);
    Rcpp::traits::input_parameter< double >::type p(pSEXP);
    Rcpp::traits::input_parameter< bool >::type modified(modifiedSEXP);
    rcpp_result_gen = Rcpp::wrap(gd_c(A, B, p, modified));
    return rcpp_result_gen;
END_RCPP
}
// gdp_c
double gdp_c(NumericMatrix A, NumericMatrix B, double p, bool modified);
RcppExport SEXP _ecr3vis_gdp_c(SEXP ASEXP, SEXP BSEXP, SEXP pSEXP, SEXP modifiedSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type A(ASEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type B(BSEXP);
    Rcpp::traits::input_parameter< double >::type p(pSEXP);
    Rcpp::traits::input_parameter< bool >::type modified(modifiedSEXP);
    rcpp_result_gen = Rcpp::wrap(gdp_c(A, B, p, modified));
    return rcpp_result_gen;
END_RCPP
}

RcppExport SEXP dominated_c(SEXP);
RcppExport SEXP hv_c(SEXP, SEXP);
RcppExport SEXP hv_contr_c(SEXP, SEXP);
RcppExport SEXP nds_c(SEXP);

static const R_CallMethodDef CallEntries[] = {
    {"_ecr3vis_gd_c", (DL_FUNC) &_ecr3vis_gd_c, 4},
    {"_ecr3vis_gdp_c", (DL_FUNC) &_ecr3vis_gdp_c, 4},
    {"dominated_c",    (DL_FUNC) &dominated_c,    1},
    {"hv_c",           (DL_FUNC) &hv_c,           2},
    {"hv_contr_c",     (DL_FUNC) &hv_contr_c,     2},
    {"nds_c",          (DL_FUNC) &nds_c,          1},
    {NULL, NULL, 0}
};

RcppExport void R_init_ecr3vis(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
