# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

gd_c <- function(A, B, p, modified) {
    .Call(`_ecr3vis_gd_c`, A, B, p, modified)
}

gdp_c <- function(A, B, p, modified) {
    .Call(`_ecr3vis_gdp_c`, A, B, p, modified)
}

