# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cov_c <- function(A, B) {
    .Call(`_ecr3vis_cov_c`, A, B)
}

os_c <- function(A, np, ip) {
    .Call(`_ecr3vis_os_c`, A, np, ip)
}

rse_c <- function(A, s) {
    .Call(`_ecr3vis_rse_c`, A, s)
}

gd_c <- function(A, B, p, modified) {
    .Call(`_ecr3vis_gd_c`, A, B, p, modified)
}

gdp_c <- function(A, B, p, modified) {
    .Call(`_ecr3vis_gdp_c`, A, B, p, modified)
}

